name: Docker Images

on:
  schedule:
   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  ghcr:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:master
      -
        name: Build GHCR images
        env:
          DOCKER_REPO: ghcr.io/${{ github.actor }}/s3fs
          SOURCE_COMMIT: ${{ github.sha }}
        run: ./hooks/build
  hub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:master
      -
        name: Build Docker Hub images
        env:
          DOCKER_REPO: docker.io/linuxcontainers/s3fs
          SOURCE_COMMIT: ${{ github.sha }}
        run: ./hooks/build
      -
        # Note: This uses the password or token
        name: Update repo description at Docker Hub
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: linuxcontainers/s3fs
          short-description: Mount S3 buckets from within a container and expose them to host/containers
